# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_GITHUB_REPO_URL
ARG VITE_GITHUB_TOKEN
ARG VITE_OPENAI_API_KEY

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_GITHUB_REPO_URL=$VITE_GITHUB_REPO_URL
ENV VITE_GITHUB_TOKEN=$VITE_GITHUB_TOKEN
ENV VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY

COPY package*.json ./
RUN npm ci
COPY . .

RUN npm run build